/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv ./cloudflare-env.d.ts` (hash: 9c2f9ad83c9e4ebb2e6ff78d430b99b2)
interface __BaseEnv_CloudflareEnv {
	REVIEW_PACKAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ENV: "staging" | "production" | "local";
	STRIPE_EXPECTED_ACCOUNT_ID?: "acct_1MwbFJI9EPtyKcIs";
	BETTER_AUTH_SECRET: string;
	TEST_BILLING_WEBHOOK_SECRET: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_PASS_PRICE_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface StagingEnv {
		REVIEW_PACKAGES: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		APP_ENV: "staging";
		STRIPE_EXPECTED_ACCOUNT_ID: "acct_1MwbFJI9EPtyKcIs";
		BETTER_AUTH_SECRET: string;
		TEST_BILLING_WEBHOOK_SECRET: string;
		STRIPE_SECRET_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		STRIPE_PASS_PRICE_ID: string;
	}
	interface ProductionEnv {
		REVIEW_PACKAGES: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		APP_ENV: "production";
		BETTER_AUTH_SECRET: string;
		TEST_BILLING_WEBHOOK_SECRET: string;
		STRIPE_SECRET_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		STRIPE_PASS_PRICE_ID: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "STRIPE_EXPECTED_ACCOUNT_ID" | "BETTER_AUTH_SECRET" | "TEST_BILLING_WEBHOOK_SECRET" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "STRIPE_PASS_PRICE_ID">> {}
}
