/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv ./cloudflare-env.d.ts` (hash: 1a7dbddc7564b0fdeabb441b24124046)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ENV: "staging" | "production" | "local";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface StagingEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		APP_ENV: "staging";
	}
	interface ProductionEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		APP_ENV: "production";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV">> {}
}
